### ISSUE TITLE
Does the plug-in support IntelliCenter panel version 2.017?

### ISSUE THREAD

**Issue by nickcurmi** [dustindclark/homebridge-pentair-intellicenter#149]
**Is your feature request related to a problem? Please describe:**
My panel keeps recommending an update to 2.017. Wasn’t sure if this plug-in would support it, so I’m ignoring the update for now. Is this plug-in confirmed to work with the latest version?

**Describe the solution you'd like:**
Support for the latest panel version

**Describe alternatives you've considered:**
Remaining on 1.064

**Additional context:**
N/A

**Comment by mssiemer** [comment]
After upgrading My IntelliCenter from 1.064 to 2.019, not only did the pool accessories quit updating, but all accessories. Only when I disable the IntelliCenter plug-in does my HomeBridge work. I've done all the usual early debugging (reboot everything, individually unload and reload each plugins, try child bridge, etc). Whenever the IntelliCenter plug-in is enabled everything quits with no errors other than a couple of "400" unknown response errors from the plug-in.

**Comment by mssiemer** [comment]
[22/11/2023, 02:21:19] [PentairIntelliCenter] Received unsuccessful response code 400 from IntelliCenter. Message: {
  "command": "Error",
  "messageID": "5af3c332-b01c-4537-ba6a-63226b53398e",
  "response": "400",
  "description": "ParseError: unexpected end of input in string"
}
[22/11/2023, 02:21:19] [PentairIntelliCenter] Received unsuccessful response code 400 from IntelliCenter. Message: {
  "command": "Error",
  "messageID": "8104b6a3-6f80-49ed-853b-34b37f5ed411",
  "response": "400",
  "description": "ParseError: expected value, got 'b' (98)"
}

**Comment by atxwaldo** [comment]
I'm having the same issue after upgrade to IntelliCenter 2.017. Any help or advice is much appreciated. Thanks in advance.

**Comment by dustindclark** [comment]
I've been running on 2.017 without any issues. With any upgrade, make sure that you reboot your IntelliCenter (cut power to both your control panel and your wireless pentair connector if applicable), and then subsequently restart HomeBridge after the IntelliCenter is back up. I also have to then open/close my pool cover. Otherwise, circuits that should be disabled when the cover is closed seem to be enabled (IntelliCenter problem).

**Comment by mssiemer** [comment]
Hi Dustin,

Thanks for responding.  I had reboot both ends before, but did it again. I’m using the IP address, e-mail address, and password that is configured on the device and web-site. Pentair’s iOS app and web portal both work.

-M


 Finished waiting. Attempting reconnect...
[30/12/2023, 16:43:16] [PentairIntelliCenter] Received unsuccessful response code 400 from IntelliCenter. Message: {
  "command": "SendQuery",
  "messageID": "41ac5275-9962-42fd-b558-e7bcd3e9f317",
  "response": "400"
}

**Comment by mssiemer** [comment]
[30/12/2023, 16:51:40] [PentairIntelliCenter] Received unsuccessful response code 400 from IntelliCenter. Message: {
  "command": "Error",
  "messageID": "b72146d8-d787-40d1-8765-dce11daaf009",
  "response": "400",
  "description": "ParseError: unexpected end of input in string"
}

[30/12/2023, 16:51:40] [PentairIntelliCenter] Received unsuccessful response code 400 from IntelliCenter. Message: {
  "command": "Error",
  "messageID": "396a88a1-8991-463b-bcb1-915b18263bb6",
  "response": "400",
  "description": "ParseError: expected value, got 'b' (98)"
}

**Comment by mssiemer** [comment]
Error: Cannot connect
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:87:25)
    at Object.onceWrapper (node:events:628:28)
    at Socket.emit (node:events:514:28)
    at Socket._onTimeout (node:net:589:8)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)

[30/12/2023, 16:42:14] [PentairIntelliCenter] IntelliCenter socket has been closed. Waiting 30 seconds and attempting to reconnect...

[30/12/2023, 16:42:14] [PentairIntelliCenter] Caught error in sendCommandNoWait for command {
  "command": "GetQuery",
  "queryName": "GetHardwareDefinition",
  "arguments": "CIRCUITS",
  "messageID": "d7b9156b-168f-4497-a807-a2deaae59c4e"
} Error: socket not writable
    at /usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:264:16
    at Promise._execute (/usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:103:10)
    at Telnet.send (/usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:216:12)
    at PentairPlatform.sendCommandNoWait (/usr/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:448:21)
    at PentairPlatform.discoverDeviceType (/usr/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:305:10)
    at PentairPlatform.discoverDevices (/usr/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:294:10)
    at /usr/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:167:18

[30/12/2023, 16:42:44] [PentairIntelliCenter] Finished waiting. Attempting reconnect...

[30/12/2023, 16:42:45] [PentairIntelliCenter] IntelliCenter socket error has been detected. Socket will be closed. Cannot connect

[30/12/2023, 16:42:45] [PentairIntelliCenter] Connection to IntelliCenter failed. Check config: {
  "host": "10.0.1.50",
  "port": 6681,
  "negotiationMandatory": false,
  "timeout": 1500,
  "debug": true,
  "username": ***@***.***",
  "password": “xxxxxxxxx."
} Error: Cannot connect
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:87:25)
    at Object.onceWrapper (node:events:628:28)
    at Socket.emit (node:events:514:28)
    at Socket._onTimeout (node:net:589:8)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)

[30/12/2023, 16:42:45] [PentairIntelliCenter] IntelliCenter socket has been closed. Waiting 30 seconds and attempting to reconnect...

[30/12/2023, 16:42:45] [PentairIntelliCenter] Caught error in sendCommandNoWait for command {
  "command": "GetQuery",
  "queryName": "GetHardwareDefinition",
  "arguments": "CIRCUITS",
  "messageID": "20aa19cf-cfe7-40ec-bf05-afecdf8670a1"
} Error: socket not writable
    at /usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:264:16
    at Promise._execute (/usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:103:10)
    at Telnet.send (/usr/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:216:12)
    at PentairPlatform.sendCommandNoWait (/usr/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:448:21)
    at PentairPlatform.discoverDeviceType (/usr/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:305:10)
    at PentairPlatform.discoverDevices (/usr/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:294:10)
    at /usr/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:167:18

[30/12/2023, 16:43:15] [PentairIntelliCenter] Finished waiting. Attempting reconnect...

[30/12/2023, 16:43:16] [PentairIntelliCenter] Received unsuccessful response code 400 from IntelliCenter. Message: {
  "command": "SendQuery",
  "messageID": "41ac5275-9962-42fd-b558-e7bcd3e9f317",
  "response": "400"
}

**Comment by mssiemer** [comment]
Dustin,

I am an embedded engineer and if there is anything I can do to test or help just let me know.

-Michael
405-808-5380

**Comment by dustindclark** [comment]
The message seems to indicate that we sent invalid JSON to IntelliCenter:

```
[30/12/2023, 16:51:40] [PentairIntelliCenter] Received unsuccessful response code 400 from IntelliCenter. Message: {
  "command": "Error",
  "messageID": "396a88a1-8991-463b-bcb1-915b18263bb6",
  "response": "400",
  "description": "ParseError: expected value, got 'b' (98)"
}
```

The only way to verify is turn on debug mode and inspect the message that was sent to IntelliCenter for the corresponding messageID (`396a88a1-8991-463b-bcb1-915b18263bb6`).  If you can post that, we should be able to figure out what the problem is. I think the other messages about the socket not being writable are just side effects of this failure, but we need to get past this error to confirm.

**Comment by mssiemer** [comment]
Reverted back to Intellicenter 1.064 and Homebridge is working. There’s still the error message in the log, but everything is functional. I noticed with 2.019 the Intellicenter 2 iOS app quit working, but the new Pentair Home app worked. Going back to 1.x the Intelicenter app works again.

-M

**Comment by Kevin-61** [comment]
I also started getting this error since version 2.1.0.  Not sure what is going on since everything seems to work,

Just to avoid the error I backed down to v 2.0.11

Also, it would be nice to have an option to disable the vaiable speed option in pumps.


K
