### ISSUE TITLE
In Bridge Mode, Socket Not Writable

### ISSUE THREAD

**Issue by cjsfj** [dustindclark/homebridge-pentair-intellicenter#2]
**Describe The Bug:**
When the plugin starts in bridge mode, it is not able to start, citing socket errors

**To Reproduce:**
Start the plugin in Bridge mode. If already in Bridge mode, restart Homebridge. To resolve, Turn Bridge mode off; restart Homebridge; re-enable Bridge mode; restart Homebridge.

**Expected behavior:**
The plugin should not have socket errors in Bridge mode.

**Logs:**

```
[1/2/2022, 6:36:30 PM] [homebridge-pentair-intellicenter] IntelliCenter socket error has been detected. Socket will be closed. Cannot connect
[1/2/2022, 6:36:30 PM] [homebridge-pentair-intellicenter] Connection to IntelliCenter failed. Check config: {
  "host": "192.168.2.68",
  "port": 6681,
  "negotiationMandatory": false,
  "timeout": 1500,
  "debug": true,
  "username": "<<redacted>>",
  "password": "<<redacted>>"
} Error: Cannot connect
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:87:25)
    at Object.onceWrapper (node:events:509:28)
    at Socket.emit (node:events:390:28)
    at Socket._onTimeout (node:net:501:8)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
[1/2/2022, 6:36:30 PM] [homebridge-pentair-intellicenter] IntelliCenter socket has been closed. Waiting 30 seconds and attempting to reconnect...
[1/2/2022, 6:36:30 PM] [homebridge-pentair-intellicenter] Caught error in sendCommandNoWait for command {
  "command": "GetQuery",
  "queryName": "GetHardwareDefinition",
  "arguments": "",
  "messageID": "cbd8f2d5-bb2e-43ba-816a-7f570c42279a"
} Error: socket not writable
    at /usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:264:16
    at Promise._execute (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:103:10)
    at Telnet.send (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:216:12)
    at PentairPlatform.sendCommandNoWait (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:372:21)
    at PentairPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:261:10)
    at /usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:148:18
[1/2/2022, 6:37:00 PM] [homebridge-pentair-intellicenter] Finished waiting. Attempting reconnect...
```

**Plugin Config:**

```json
{
    "ipAddress": "192.168.2.68",
    "username": "<<redacted>>",
    "password": "<<redacted>>",
    "temperatureUnits": "F",
    "minimumTemperature": 50,
    "maximumTemperature": 104,
    "_bridge": {
        "username": "0E:99:48:15:B1:54",
        "port": 30708
    },
    "platform": "PentairIntelliCenter"
}
```

**Screenshots:**
n/a

**Environment:**

* **Plugin Version**: 1.0.26
* **Homebridge Version**: 1.3.9
* **Node.js Version**: 16.13.1
* **NPM Version**: 8.1.2
* **Operating System**: macOS

**Comment by dustindclark** [comment]
I've been running in bridge mode for a while now without any issues. Try restarting your panel, and then restart Homebridge. The panel can be finicky about closing old connections.

Dustin

**Comment by cjsfj** [comment]
I rebooted the panel bridge to my home network and all seems well. You're totally right that it can be finicky and I should have thought of that ;)
