### ISSUE TITLE
Accessories Disapeared from UI/X

### ISSUE THREAD

**Issue by nickcurmi** [dustindclark/homebridge-pentair-intellicenter#92]
**Describe The Bug:**
Accessories disappeared from accessories pane in UI/X. Errors showing in logs. 

**To Reproduce:**
Occurring consistently without any action taken. 

**Expected behavior:**
Accessories to be available and function normally. 

**Logs:**

[12/01/2023, 15:58:01] [homebridge-pentair-intellicenter] Sending fire and forget command to IntelliCenter: {"command":"GetQuery","queryName":"GetHardwareDefinition","arguments":"CIRCUITS","messageID":"be3a8c6e-97e6-42b0-842b-39525018274c"}
[12/01/2023, 15:58:01] [homebridge-pentair-intellicenter] IntelliCenter socket has been closed. Waiting 30 seconds and attempting to reconnect...
[12/01/2023, 15:58:01] [homebridge-pentair-intellicenter] Caught error in sendCommandNoWait for command {
  "command": "GetQuery",
  "queryName": "GetHardwareDefinition",
  "arguments": "CIRCUITS",
  "messageID": "be3a8c6e-97e6-42b0-842b-39525018274c"
} Error: socket not writable
    at /usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:264:16
    at Promise._execute (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:103:10)
    at Telnet.send (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:216:12)
    at PentairPlatform.sendCommandNoWait (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:397:21)
    at PentairPlatform.discoverDeviceType (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:269:10)
    at PentairPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:258:10)
    at /usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:151:18
[12/01/2023, 15:58:31] [homebridge-pentair-intellicenter] Finished waiting. Attempting reconnect...
[12/01/2023, 15:58:31] [homebridge-pentair-intellicenter] IntelliCenter socket error has been detected. Socket will be closed. Error: connect ENETUNREACH xxx.xxx.x.xx:xxxx - Local (0.0.0.0:0)
[12/01/2023, 15:58:31] [homebridge-pentair-intellicenter] Connection to IntelliCenter failed. Check config: {
  "host": "xxx.xxx.x.xx",
  "port": xxxx,
  "negotiationMandatory": false,
  "timeout": 1500,
  "debug": true,
  "username": "x",
  "password": "x"
} Error: connect ENETUNREACH xxx.xxx.x.xx:xxxx - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: 'xxx.xxx.x.xx',
  port: xxxx
}
[12/01/2023, 15:58:31] [homebridge-pentair-intellicenter] Sending fire and forget command to IntelliCenter: {"command":"GetQuery","queryName":"GetHardwareDefinition","arguments":"CIRCUITS","messageID":"8b8e5b64-cd13-401a-9b7d-773629f9e139"}
[12/01/2023, 15:58:31] [homebridge-pentair-intellicenter] IntelliCenter socket has been closed. Waiting 30 seconds and attempting to reconnect...
[12/01/2023, 15:58:31] [homebridge-pentair-intellicenter] Caught error in sendCommandNoWait for command {
  "command": "GetQuery",
  "queryName": "GetHardwareDefinition",
  "arguments": "CIRCUITS",
  "messageID": "8b8e5b64-cd13-401a-9b7d-773629f9e139"
} Error: socket not writable
    at /usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:264:16
    at Promise._execute (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:103:10)
    at Telnet.send (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:216:12)
    at PentairPlatform.sendCommandNoWait (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:397:21)
    at PentairPlatform.discoverDeviceType (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:269:10)
    at PentairPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:258:10)
    at /usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:151:18
[12/01/2023, 15:59:01] [homebridge-pentair-intellicenter] Finished waiting. Attempting reconnect...
[12/01/2023, 15:59:01] [homebridge-pentair-intellicenter] IntelliCenter socket error has been detected. Socket will be closed. Error: connect ENETUNREACH xxx.xxx.x.xx:xxxx - Local (0.0.0.0:0)
[12/01/2023, 15:59:01] [homebridge-pentair-intellicenter] Connection to IntelliCenter failed. Check config: {
  "host": "xxx.xxx.x.xx",
  "port": xxxx,
  "negotiationMandatory": false,
  "timeout": 1500,
  "debug": true,
  "username": "x",
  "password": "x"
} Error: connect ENETUNREACH xxx.xxx.x.xx:xxxx - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: 'xxx.xxx.x.xx',
  port: xxxx
}
[12/01/2023, 15:59:01] [homebridge-pentair-intellicenter] Sending fire and forget command to IntelliCenter: {"command":"GetQuery","queryName":"GetHardwareDefinition","arguments":"CIRCUITS","messageID":"2b5fd352-25b0-4413-9a89-94df506a8f71"}
[12/01/2023, 15:59:01] [homebridge-pentair-intellicenter] IntelliCenter socket has been closed. Waiting 30 seconds and attempting to reconnect...
[12/01/2023, 15:59:01] [homebridge-pentair-intellicenter] Caught error in sendCommandNoWait for command {
  "command": "GetQuery",
  "queryName": "GetHardwareDefinition",
  "arguments": "CIRCUITS",
  "messageID": "2b5fd352-25b0-4413-9a89-94df506a8f71"
} Error: socket not writable
    at /usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:264:16
    at Promise._execute (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:103:10)
    at Telnet.send (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:216:12)
    at PentairPlatform.sendCommandNoWait (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:397:21)
    at PentairPlatform.discoverDeviceType (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:269:10)
    at PentairPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:258:10)
    at /usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:151:18
[12/01/2023, 15:59:31] [homebridge-pentair-intellicenter] Finished waiting. Attempting reconnect...
[12/01/2023, 15:59:31] [homebridge-pentair-intellicenter] IntelliCenter socket error has been detected. Socket will be closed. Error: connect ENETUNREACH xxx.xxx.x.xx:xxxx - Local (0.0.0.0:0)
[12/01/2023, 15:59:31] [homebridge-pentair-intellicenter] Connection to IntelliCenter failed. Check config: {
  "host": "xxx.xxx.x.xx",
  "port": xxxx,
  "negotiationMandatory": false,
  "timeout": 1500,
  "debug": true,
  "username": "x",
  "password": "x"
} Error: connect ENETUNREACH xxx.xxx.x.xx:xxxx - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: 'xxx.xxx.x.xx',
  port: xxxx
}
[12/01/2023, 15:59:31] [homebridge-pentair-intellicenter] Sending fire and forget command to IntelliCenter: {"command":"GetQuery","queryName":"GetHardwareDefinition","arguments":"CIRCUITS","messageID":"1217c854-f417-469c-b454-eded494c28f4"}
[12/01/2023, 15:59:31] [homebridge-pentair-intellicenter] IntelliCenter socket has been closed. Waiting 30 seconds and attempting to reconnect...
[12/01/2023, 15:59:31] [homebridge-pentair-intellicenter] Caught error in sendCommandNoWait for command {
  "command": "GetQuery",
  "queryName": "GetHardwareDefinition",
  "arguments": "CIRCUITS",
  "messageID": "1217c854-f417-469c-b454-eded494c28f4"
} Error: socket not writable
    at /usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:264:16
    at Promise._execute (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/bluebird/js/release/promise.js:103:10)
    at Telnet.send (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/node_modules/telnet-client/lib/index.js:216:12)
    at PentairPlatform.sendCommandNoWait (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:397:21)
    at PentairPlatform.discoverDeviceType (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:269:10)
    at PentairPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:258:10)
    at /usr/local/lib/node_modules/homebridge-pentair-intellicenter/src/platform.ts:151:18

**Plugin Config:**

{
    "bridge": {
        "name": "Homebridge 7470",
        "username": "x",
        "port": x,
        "pin": "x"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": x,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "ipAddress": "xxx.xxx.x.xx",
            "username": "x",
            "password": "x",
            "temperatureUnits": "F",
            "minimumTemperature": 35,
            "maximumTemperature": 105,
            "_bridge": {
                "username": "x",
                "port": x
            },
            "platform": "PentairIntelliCenter"
        },
        {
            "name": "Home Alarm",
            "cameras": false,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        }
    ]
}

**Screenshots:**

**Environment:**

* **Plugin Version**: v2.0.11
* **Homebridge Version**: HB Version v1.6.0 UI/X version v4.50.2
* **Node.js Version**: v16.14.0
* **NPM Version**: 8.3.1
* **Operating System**:  Raspbian GNU/Linux Buster

**Comment by nickcurmi** [comment]
This issue suddenly resolved last night and it’s working again. Not sure what changed. Going to close this issue.
